In [1]:
import os

In [2]:
print (os.getcwd())

f:\guvi

In [1]:
%pip install gitpython

Requirement already satisfied: gitpython in .\.venv\lib\site-packages (3.1.44)
Requirement already satisfied: gitdb<5,>=4.0.1 in .\.venv\lib\site-packages (from gitpython) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in .\.venv\lib\site-packages (from gitdb<5,>=4.0.1->gitpython) (5.0.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:

import git
repo_url="https://github.com/PhonePe/pulse.git"
clone_dir="phonepe_pulse_data"
git.Repo.clone_from(repo_url,clone_dir)
print("cloned")

GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/PhonePe/pulse.git phonepe_pulse_data
  stderr: 'fatal: destination path 'phonepe_pulse_data' already exists and is not an empty directory.
'

In [1]:
import pandas as pd
import os
path="phonepe_pulse_data/data/aggregated/transaction/country/india/state/"
agg_state_list=os.listdir(path)
agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [3]:
import json

In [4]:

clm={"state":[],"year":[],"quarter":[],"transaction_type":[],"transaction_count":[],"transaction_amount":[]}
for i in agg_state_list:
    p_i=path+i+"/"
    agg_year=os.listdir(p_i)
    #print(agg_year_list)
    #print(f"{i}: {len(agg_year_list)}")
    for j in agg_year:
        p_j=p_i+j+"/"
        agg_year_list=os.listdir(p_j)
        for k in agg_year_list:
            p_k=p_j+k
            data=open(p_k,'r')
            D=json.load(data)
            for z in D["data"]["transactionData"]:
                name=z["name"]
                count=z["paymentInstruments"][0]["count"]
                amount=z["paymentInstruments"][0]["amount"]
                clm["transaction_amount"].append(amount)
                clm["transaction_count"].append(count)
                clm["transaction_type"].append(name)
                clm["state"].append(i)
                clm["year"].append(j)
                clm["quarter"].append(int(k.strip('.json')))
agg_transaction=pd.DataFrame(clm)

In [5]:
agg_transaction

,state,year,quarter,transaction_type,transaction_count,transaction_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [6]:
path="phonepe_pulse_data/data/aggregated/user/country/india/state/" 
agg_user_state=os.listdir(path)

#agg_user_state

In [7]:

clm1={"state":[],"year":[],"quarter":[],"registered_user":[],"appsopen":[],"brand":[],"brand_count":[]}
for i in agg_user_state:
    p_i=path+i+"/"
    agg_user_year=os.listdir(p_i)
    #print(agg_year_list)
    #print(f"{i}: {len(agg_year_list)}")
    for j in agg_user_year:
        p_j=p_i+j+"/"
        agg_user_year_list=os.listdir(p_j)
        for k in agg_user_year_list:
            p_k=p_j+k
            #print(p_k)
            data=open(p_k,'r')
            D1=json.load(data)
            print(D1)
            #reg_user=D1.get("data",{}).get("aggregated",{}).get("registeredUsers",0)
            #app_open=D1.get("data",{}).get("aggregated",{}).get("appOpens",0)
            #user_by_device=D1.get("data",{}).get("usersByDevice",[])

            #if not isinstance (user_by_device,list):
                #user_by_device=[]
            for z in user_by_device:
                brand_name=z.get("brand","unknown")
                brand_cnt=z.get("count",0)
                
                clm1["registered_user"].append(reg_user)
                clm1["appsopen"].append(app_open)
                clm1["brand"].append(brand_name)
                clm1["brand_count"].append(brand_cnt)
                clm1["state"].append(i)
                clm1["year"].append(j)
                clm1["quarter"].append(int(k.strip('.json')))
agg_user=pd.DataFrame(clm1)

{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 6740, 'appOpens': 0}, 'usersByDevice': [{'brand': 'Xiaomi', 'count': 1665, 'percentage': 0.2470326409495549}, {'brand': 'Samsung', 'count': 1445, 'percentage': 0.21439169139465875}, {'brand': 'Vivo', 'count': 982, 'percentage': 0.1456973293768546}, {'brand': 'Oppo', 'count': 501, 'percentage': 0.07433234421364986}, {'brand': 'OnePlus', 'count': 332, 'percentage': 0.04925816023738872}, {'brand': 'Realme', 'count': 316, 'percentage': 0.04688427299703264}, {'brand': 'Apple', 'count': 229, 'percentage': 0.03397626112759644}, {'brand': 'Motorola', 'count': 226, 'percentage': 0.03353115727002967}, {'brand': 'Lenovo', 'count': 202, 'percentage': 0.02997032640949555}, {'brand': 'Huawei', 'count': 158, 'percentage': 0.02344213649851632}, {'brand': 'Others', 'count': 684, 'percentage': 0.10148367952522255}]}, 'responseTimestamp': 1630501494543}

NameError: name 'user_by_device' is not defined

In [8]:
agg_user["year"].unique()

NameError: name 'agg_user' is not defined

In [34]:
if "2019" in agg_user["year"].values:
    print("Yes exists in the DataFrame!")
else:
    print("no")

Yes exists in the DataFrame!

In [10]:
path_map_tran="phonepe_pulse_data/data/map/transaction/hover/country/india/state/" 
map_tran=os.listdir(path_map_tran)
map_tran

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [11]:
clm2={"state":[],"year":[],"quarter":[],"district":[],"total_num_transaction":[],"total_transaction_amount":[]}
for i in map_tran:
    #print(i)
    m_i=path_map_tran+i+'/'
    #print(m_i)
    map_tran_year=os.listdir(m_i)
    #print(map_user_year)
    for j in map_tran_year:
        m_j=m_i+j+'/'
        map_tran_year_quarter=os.listdir(m_j)
        #print(map_user_year_quarter)
        for  k in map_tran_year_quarter:
            m_k=m_j+k
            #print(m_k)
            data=open(m_k,'r')
            #print(data)
            map_data=json.load(data)
            #print(map_data)
            for z in map_data["data"]["hoverDataList"]:
                district_name=z["name"]
                num_of_transaction=z["metric"][0]["count"]
                total_tran_amount=z["metric"][0]["amount"]
                #(num_of_transaction)
                clm2["state"].append(i)
                clm2["year"].append(j)
                clm2["quarter"].append(int(k.strip(".json")))
                clm2["district"].append(district_name)
                clm2["total_num_transaction"].append(num_of_transaction)
                clm2["total_transaction_amount"].append(total_tran_amount)
map_tansaction=pd.DataFrame(clm2)

In [12]:
map_tansaction

,state,year,quarter,district,total_num_transaction,total_transaction_amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,9395,2.394824e+07
...,...,...,...,...,...,...
20599,west-bengal,2024,4,alipurduar district,15875637,2.099251e+10
20600,west-bengal,2024,4,paschim bardhaman district,56616799,6.968735e+10
20601,west-bengal,2024,4,nadia district,65274337,1.079320e+11
20602,west-bengal,2024,4,birbhum district,36905213,5.778701e+10
20603,west-bengal,2024,4,purba medinipur district,67833775,1.142771e+11

In [13]:
map_user_path="phonepe_pulse_data/data/map/user/hover/country/india/state/"
map_user=os.listdir(map_user_path)
map_user

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [26]:
clm3={"state":[],"year":[],"quarter":[],"district":[],"register_user":[],"apps_open":[]}
for i in map_user:
    p_i=map_user_path+i+'/'
    #print(p_i)
    map_user_year=os.listdir(p_i)
    #print(map_user_year)
    for j in map_user_year:
        p_j=p_i+j+'/'
        #print(p_j)
        map_user_quarter=os.listdir(p_j)
        #print(map_user_quarter)
        for k in map_user_quarter:
            p_k=p_j+k
            data=open(p_k,'r')
            map_user_data=json.load(data)
            for z in map_user_data["data"]["hoverData"]:
                district_name=z
                reg_user=map_user_data["data"]["hoverData"][z]["registeredUsers"]
                open_app_count=map_user_data["data"]["hoverData"][z]["appOpens"]
                clm3["state"].append(i)
                clm3["year"].append(j)
                clm3["quarter"].append(int(k.strip(".json")))
                clm3["district"].append(district_name)  
                clm3["register_user"].append(reg_user)
                clm3["apps_open"].append(open_app_count)
map_users=pd.DataFrame(clm3)

In [27]:
map_users

,state,year,quarter,district,register_user,apps_open
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,west-bengal,2024,4,alipurduar district,475688,31842355
20604,west-bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,west-bengal,2024,4,nadia district,1861738,98740305
20606,west-bengal,2024,4,birbhum district,1114220,73465525
20607,west-bengal,2024,4,purba medinipur district,1717074,108350777

In [31]:
top_path="phonepe_pulse_data/data/top/transaction/country/india/state/"
top_tran=os.listdir(top_path)
top_tran

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [33]:
for i in top_path:
    p_i=top_path+i+'/'
    top_tran_year=os.listdir(p_i)
    print(top_tran_year)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'phonepe_pulse_data/data/top/transaction/country/india/state/p/'